server.port=8082
spring.application.name=ms-pedidos360-catalog

# Usa exactamente la misma ruta del Wallet y el mismo TNS que usaste para orders
spring.datasource.url=jdbc:oracle:thin:@pedidos360orders_tp?TNS_ADMIN=C:/Wallet360/Wallet_pedidos360orders

# AQUI ESTA LA MAGIA: Usamos el esquema aislado del catálogo
spring.datasource.username=PEDIDOS_CATALOG
spring.datasource.password=17deAcuario#07
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate creará las tablas de Productos automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

# Fallback H2 opcional para pruebas locales sin conexión
# spring.datasource.url=jdbc:h2:mem:catalogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
