server.port=${PORT:8082}
spring.application.name=ms-pedidos360-catalog

# Conexión Oracle Autonomous Database con variables de entorno
spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME:pedidos360orders_tp}?TNS_ADMIN=${TNS_ADMIN:C:/Wallet360/Wallet_pedidos360orders}
spring.datasource.username=${DB_USER:PEDIDOS_CATALOG}
spring.datasource.password=${DB_PASSWORD:17deAcuario#07}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
